---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mynewconfig
data:
  color: "red"
  bgcolor: "{{ .Values.myval }}"
---
apiVersion: v1
kind: Pod
metadata:
  name: mytestpod
spec:
  containers:
  - name: test
    image: ubuntu
    command:
    - "sh"
    - "-c"
    - "sleep 1000"
